# Generated by Django 4.2.3 on 2023-07-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Registro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locales",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
